### ISSUE TITLE
where I find iconv.h file?

### ISSUE THREAD

**Issue by Jaehaks** [lunarmodules/lua-iconv#14]
Thank you for your efforts, 

When I install lua-iconv using luarocks, It requires iconv.h like this

![image](https://github.com/lunarmodules/lua-iconv/assets/26200835/a8a2eaa8-b21b-4935-87df-9bf88976c4a2)

I cannot find any iconv.h file in lua installed directory in [lua](https://github.com/lua/lua)

**Comment by ittner** [comment]
Hi,

iconv.h is distributed as part of libc development packages in Linux distros. My resources to debug Windows issues are limited but, from the screenshot, the rock is being built locally with mingw (as expected, as there are no Windows binary distribution for lua-iconv). Have you checked if your mingw install has the development components too?

**Comment by Jaehaks** [comment]
@ittner 

I install mingw with scoop and there are iconv.h 
I added the path to external_deps_dirs of luarocks's config in cmd prompt
`luarocks config external_deps_dirs[2] %USERPROFILE%\scoop\apps\mingw\current\x86_64-w645-mingw32`

And then `luarocks install lua-iconv` works 
Thank you for you reply :)
