### ISSUE TITLE
./iconv.so: undefined symbol: libiconv

### ISSUE THREAD

**Issue by randall05** [lunarmodules/lua-iconv#3]
when i run the test_iconv.lua, i get error below:
# /usr/local/lua-5.1.4/bin/lua /root/lua-iconv/test_iconv.lua

/usr/local/lua-5.1.4/bin/lua: error loading module 'iconv' from file './iconv.so':
        ./iconv.so: undefined symbol: libiconv
stack traceback:
        [C]: ?
        [C]: in function 'require'
        /root/lua-iconv/test_iconv.lua:1: in main chunk
        [C]: ?

i am sure i have been installed libiconv-1.13.1, it is in /usr/local/iconv-1.13.1, and:
# ldconfig -p|grep iconv

```
    libiconv.so.2 (libc6,x86-64) => /usr/local/libiconv-1.13.1/lib/libiconv.so.2
    libiconv.so (libc6,x86-64) => /usr/local/libiconv-1.13.1/lib/libiconv.so
```

can you help me ?

**Comment by wty717** [comment]
iconv.lua:21: in main chunk
