### ISSUE TITLE
Cannot install on OSX

### ISSUE THREAD

**Issue by richardipsum** [lunarmodules/lua-iconv#6]
Hi, I recently packaged your library for NixOS, the CI builds Darwin as well as Linux by default. There seem to be a number of issues that prevent this from working with OSX.

I fixed a bunch of things but finally when I try to run the example.lua file included in this git repo I get the following:

    sh-3.2# lua test_iconv.lua 
    lua: error loading module 'iconv' from file '/usr/local/lib/lua/5.2/iconv.so':
            dlopen(/usr/local/lib/lua/5.2/iconv.so, 6): Symbol not found: _iconv
      Referenced from: /usr/local/lib/lua/5.2/iconv.so
      Expected in: flat namespace
     in /usr/local/lib/lua/5.2/iconv.so
    stack traceback:
            [C]: in ?
            [C]: in function 'require'
            test_iconv.lua:3: in main chunk
            [C]: in ?
    
I've been able to package another lua binding on OSX without issue, I'm not sure I understand why this binding should be any different. Fwiw, I also modified the Makefile to link with libiconv, so it's not clear to me why the symbol cannot be found.

Thanks,
Richard

**Comment by alerque** [comment]
If you (or anybody) are still around and can check this now it would be appreciated. I don't have access to a macOS machine to test on but would be happy to facilitate if somebody wanted to work out what changes need to be made (if any) at this point.

**Comment by Tieske** [comment]
#12 was merged. @richardipsum you can try the dev rockspec now (on `master`). Please let me know if that works.

**Comment by Tieske** [comment]
just released 7.1, with the fix. Closing this.
